TradeSetup/urls.py
from django.contrib import admin
from django.urls import path, include
from trade.views import getTokenRequest, getBalanceRequest
from trade.upstox_views import getUpstoxToken
urlpatterns = [
    path('admin/trade/<int:pk>/token/',  getTokenRequest),
    path('admin/trade/<int:pk>/<str:broker>/balance/',  getBalanceRequest),
    path('admin/trade/<int:pk>/<str:broker>/gentoken/', getUpstoxToken),

    path('admin/', admin.site.urls),
    path('trade/', include('trade.urls')),

]

trade/urls.py
from django.contrib import admin
from django.urls import path, include
from . import  views, upstox_views



urlpatterns = [    
    path('buyorder/', views.buyOrder),    
    path('buyindexorder/', views.buyindexAlertOrder),
    path('sellorder/', views.sellOrder),
    path('exitorder/<str:key>/', views.exitOrder),
    path('buystockorder/', views.buystockOrder),
    path('sellstockorder/', views.sellstockOrder), 
    path('checkprofile/', views.checkProfile),
    path('optionorder/', views.optionOrder),    
    path('exitbyid/', views.exitbyId),

    ### Upstox Urls
    path('upstox/buyorder/', upstox_views.placeOrder),  
    path('upstox/optionorder/', upstox_views.placeoptionOrder),
    path('upstox/exitorderbyid/', upstox_views.exitOrderbyId),
    path('upstox/exitall', upstox_views.exitallOrders),    
    path('upstox/stockorder/', upstox_views.upstoxStocks),
    
]

trade/models.py
from django.db import models
"""['segment', 'name', 'instrument_type',
       'instrument_key', 'lot_size',
       'asset_type', 'asset_symbol
       'trading_symbol', 'strike_price'
       ]"""
# Create your models here.
class UpstoxTradeSymbol(models.Model):
    instrument_key = models.CharField(max_length=50, blank=True, null=True)
    segment = models.CharField(max_length=50, blank=True, null=True)
    trading_symbol = models.CharField(db_index=True,max_length=50,blank=True, null=True)
    name = models.CharField(max_length=50,blank=True, null=True)
    lot_size = models.IntegerField(blank=True, null=True)
    asset_type = models.CharField(db_index=True, max_length=50, blank=True, null=True)
    asset_symbol = models.CharField(db_index=True, max_length=50, blank=True, null=True)
    instrument_type	= models.CharField(max_length=50,blank=True, null=True)
    strike_price = models.IntegerField(blank=True, null=True)
    expiry = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)



class PandLReport(models.Model):
    class Meta:
        verbose_name = 'PandL Report'
        verbose_name_plural  = 'PandL Report'


class TradeUser(models.Model):
    trader_name = models.CharField(max_length=50)
    fyer_token = models.TextField()
    fyer_key = models.CharField(max_length=50, unique=True)
    updated_at = models.DateTimeField(auto_now=True)
    mobile = models.CharField(unique=True)
    pin = models.CharField(max_length=10, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    balance = models.IntegerField(default=0)
    stock_quantity = models.IntegerField(blank=True, null=True)
    bn_option_quantity = models.IntegerField(blank=True, null=True)
    nf_option_quantity = models.IntegerField(blank=True, null=True)

    token_date = models.DateField(blank=True, null=True)
    redirect_uri = models.CharField(max_length=100, blank=True, null=True)
    secret_key = models.CharField(max_length=100, blank=True, null=True)
    symbol = models.CharField(max_length=50, blank=True, null=True)
    

    def __str__(self):
        return f'{self.trader_name}' 

class tradeResponse(models.Model):
    trade_user  = models.ForeignKey('TradeUser', related_name='trade_user', on_delete=models.CASCADE)
    response = models.TextField()
    requestpath = models.CharField(max_length=50, blank=True, null=True)
    symbol = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class strikepointMaster(models.Model):
    index = models.CharField(max_length=10)
    weekday = models.IntegerField()
    trade_round_points = models.IntegerField()
    week = models.CharField(max_length=15, blank=True, null=True)

class Transaction(models.Model):
    payload = models.TextField()
    symbol = models.CharField(max_length=50)
    qty = models.IntegerField()
    trx_id = models.CharField(max_length=30)
    trader = models.ForeignKey('TradeUser', related_name='trax_trader', on_delete=models.CASCADE)
    is_close = models.BooleanField(default=False)


class UpstoxUser(models.Model):
    trader_name = models.CharField(max_length=50)
    upstox_token = models.TextField()
    upstox_key = models.CharField(max_length=50, unique=True)
    updated_at = models.DateTimeField(auto_now=True)
    mobile = models.CharField(unique=True)
    pin = models.CharField(max_length=10, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    balance = models.IntegerField(default=0)
    stock_quantity = models.IntegerField(blank=True, null=True)
    bn_option_quantity = models.IntegerField(blank=True, null=True)
    nf_option_quantity = models.IntegerField(blank=True, null=True)
    token_date = models.DateField(blank=True, null=True)
    redirect_uri = models.CharField(max_length=100, blank=True, null=True)
    upstox_secret_key = models.CharField(max_length=100, blank=True, null=True)
    symbol = models.CharField(max_length=50, blank=True, null=True)

    # def __str__(self):
    #     return f'{self.trader_name}' 

class UpstoxOrder(models.Model):
    trader = models.ForeignKey('UpstoxUser', related_name='order_trader', on_delete=models.CASCADE)    
    order_id = models.CharField(max_length=50)
    symbol = models.CharField(max_length=50)
    index = models.CharField(max_length=20, blank=True, null=True)
    expiry = models.CharField(max_length=15, blank=True, null=True)
    product = models.CharField(max_length=5, blank=True, null=True)
    instrument_token = models.CharField(max_length=50, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    trend = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    is_open = models.BooleanField(default=True)
    closed_at = models.DateTimeField(blank=True, null=True)
    trigger_price = models.FloatField(blank=True, null=True)
    close_price = models.FloatField(blank=True, null=True)
    
class LiveFeedData(models.Model):
    symbol = models.CharField(max_length=30, blank=True, null=True)
    instrumentKey = models.CharField(max_length=30, blank=True, null=True)
    tradedate = models.DateField(max_length=15, blank=True, null=True)
    tradetime = models.TimeField(max_length=10, blank=True, null=True)
    endtime = models.TimeField(max_length=10, blank=True, null=True)
    topen = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    thigh = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    tlow = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    tclos = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    e20 = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    e50 = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    rsi = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ('symbol', 'instrumentKey', 'tradedate', 'tradetime')

trade/views.py
from django.shortcuts import render, redirect
from fyers_api import fyersModel
from fyers_apiv3 import fyersModel
import os
from rest_framework.decorators import api_view
from django.http import FileResponse, HttpResponse, JsonResponse
from rest_framework import parsers, renderers, serializers, status, viewsets
import json
import datetime
from trade.endpoints import FUND_MARGIN, ORDER_DETAILS, PLACE_ORDER
from trade.models import *
from trade.gettoken import scrappingToken
import time
from django.contrib import messages
from concurrent.futures import ThreadPoolExecutor
import requests
from django.conf import settings
import pandas as pd
from trade.utils import execute, getStrikePrice, getToken, savingResponse
import trade.MarketDataFeed_pb2 as pb

# Create your views here.

def getTokenRequest(request, pk):
    trader = TradeUser.objects.get(id=pk)
    print(trader)

    if request.method == 'POST':
        otp = request.POST.get('otp_pin')
        scrappingToken('fyers', otp, pk)
        # time.sleep(20)
        
        
        return redirect('/admin/trade/tradeuser/')
    return render(request,'trade/tokengenerate.html',{
        'trader_name': trader.trader_name
    })


def getBalanceRequest(request, pk, broker):
    if broker == 'fyers':
        trader = TradeUser.objects.get(id=pk)

        session = fyersModel.FyersModel(client_id=trader.fyer_key, token=trader.fyer_token)
        try:
            funds = session.funds()
            amount = 0
            for dt in funds['fund_limit']:
                if dt['title']=="Available Balance":
                    amount = dt['equityAmount']
                    break;
            trader.balance = amount
            trader.save()
            messages.success(request, 'Balance Updated for User : {}'.format(trader.trader_name))
        except Exception as e:
            print(str(e))
            messages.error(request, "Please check the Token for User : {}".format(trader.trader_name))
        return redirect('/admin/trade/tradeuser/')
    else:
        try:
            trader = UpstoxUser.objects.get(id=pk)
            
            url = FUND_MARGIN

            payload={}
            TOKEN_HEADERS = {
                'Accept': 'application/json',
                'Authorization': 'Bearer {}'.format(trader.upstox_token)
            }       

            response = requests.request("GET", url, headers=TOKEN_HEADERS, data=payload)
        
            response = response.json()
            balance = response['data']['equity']['available_margin']
            trader.balance = balance
            trader.save()
            messages.success(request, 'Balance Updated for User : {}'.format(trader.trader_name))
        except Exception as e:
            print(str(e))
            messages.error(request, "Please check the Token for User : {}".format(trader.trader_name))
    return redirect('/admin/trade/upstoxuser/')
  
def multiOrderExecute(user, data, qty, path):
    common_data = {
        "qty": qty,    
        "type":2,
        "side":1,
        "productType":"MARGIN",
        "limitPrice":0,
        "stopPrice":0,
        "validity":"DAY",
        "disclosedQty":0,
        "orderTag":"tag1"
    }
    if not qty:
        if 'BANKNIFTY' in data['symbol']:
            qty = user.bn_option_quantity if user.bn_option_quantity else 15
        else:
            qty = user.nf_option_quantity if user.nf_option_quantity else 25
        common_data['qty'] = qty
    data.update(common_data)
    session = fyersModel.FyersModel(client_id=user.fyer_key, token=user.fyer_token)
    try:
        _response = session.place_order(data=data)
        return user.id, user.trader_name, _response
    
    except Exception as e:
        return str(e)
    
@api_view(["GET", "POST"])
def buyindexAlertOrder(request):
    """Buy order placing for index alerts"""
    """/trade/buyindexorder/"""
    """data = {
        "symbol": "NIFTY/BANKNIFTY",
        "price": 51231, #spot price
        "qty": 15*x/25*x,
        "offlineOrder": "True/False",
        "mobile": "8977810371" #trader mobile
        "_type": "BUY"
    }"""
    print('body-----------------------', request.body)
    jsonData = json.loads(request.body)
    spot = jsonData.get('price')
    index = jsonData.get('symbol')
    quantity = jsonData.get('qty', None)
    offlineOrder = jsonData.get('offlineOrder', None)
    trend = jsonData.get('trend', None)
    mobile = jsonData.get('mobile', None) 

    if trend == "CE":
        _type = "BUY"
    else:
        _type = "SELL"
    strike = getStrikePrice(spot, index, _type)
    
    data = {
        "symbol":strike,       
        "offlineOrder":True if offlineOrder and offlineOrder == "True"  else False,
    }
    if not mobile:
        active_trader_objects = TradeUser.objects.filter(is_active=True)
    else:
        active_trader_objects = TradeUser.objects.filter(mobile=mobile)
    try:
        results = []
        with ThreadPoolExecutor(max_workers=5) as executor:
            futures = [executor.submit(multiOrderExecute, record, data, quantity, request.path) for record in active_trader_objects]
            for future in futures:
                response = future.result()
                results.append(response)
                savingResponse(response[0], response[2], request.path, data['symbol'])

        return JsonResponse({'message':'Order placed successfully','success':True, "data": results},status=status.HTTP_200_OK)
    
    except Exception as e:
        print("Some error occured in Eshwar account:", str(e))
        return JsonResponse({'message':str(e),'success':False},status=status.HTTP_200_OK)


@api_view(["GET", "POST"])
def buyOrder(request):
    """Buy order placing for index alerts"""
    """/trade/buyorder/"""
    """data = {
        "symbol": "NIFTY/BANKNIFTY",
        "price": 51231, #spot price
        "qty": 15*x/25*x,
        "offlineOrder": "True/False",
        "mobile": "8977810371" #trader mobile
    }"""
    print('body-----------------------', request.body)
    jsonData = json.loads(request.body)
    spot = jsonData.get('price')
    index = jsonData.get('symbol')
    quantity = jsonData.get('qty', None)
    offlineOrder = jsonData.get('offlineOrder', None)
    mobile = jsonData.get('mobile', None)   

    strike, qty = getStrikePrice(spot, index, 'BUY')
    _token, _key = getToken(mobile)
    tradeUser = TradeUser.objects.get(fyer_key = _key)
    if quantity:
        qty = quantity
    else:
        if index == 'BANKNIFTY':
            qty = tradeUser.bn_option_quantity
        elif index == 'NIFTY':
            qty = tradeUser.nf_option_quantity
    data = {
        "symbol":strike,
        "qty":qty,
        "type":2,
        "side":1,
        "productType":"MARGIN",
        "limitPrice":0,
        "stopPrice":0,
        "validity":"DAY",
        "disclosedQty":0,
        "offlineOrder":True if offlineOrder and offlineOrder == "True"  else False,
        "orderTag":"tag1"
    }
    print(data)
    print(tradeUser)
    session = fyersModel.FyersModel(client_id=_key, token=_token)
    try:
        response = session.exit_positions(data={})
        savingResponse(tradeUser.id, response, request.path, strike)
        
        buytrigger = True
        if response['s'] == 'ok' and 'Exit request has been' in response['message']: 
            response = session.exit_positions(data={})
            time.sleep(2)
            buytrigger = True

        elif response['s'] == 'ok' or 'no open positions' in response['message']:
            buytrigger = True
        else:
            buytrigger = False
    except Exception as e:
        buytrigger = False
        print("Some error occured  account:", str(e))

    try:
        if buytrigger:       
            _response = session.place_order(data=data)
            print(_response)
            savingResponse(tradeUser.id, _response, request.path, strike)
            return JsonResponse({'message':'Order placed successfully','success':True},status=status.HTTP_200_OK)
        else: 
            return JsonResponse({'message':'Order Not placed','success':False},status=status.HTTP_200_OK)
    except Exception as e:
        print("Some error occured in Eshwar account:", str(e))
        return JsonResponse({'message':str(e),'success':False},status=status.HTTP_200_OK)


@api_view(["GET", "POST"])
def sellOrder(request):
    """Sell order placing for index alerts"""
    """/trade/sellorder/"""
    """data = {
        "symbol": "NIFTY/BANKNIFTY",
        "price": 51231, #spot price
        "qty": 15*x/25*x, #(Optional)
        "offlineOrder": "True/False",
        "mobile": "8977810371" #trader mobile #(Optional)
    }"""
    print('body-----------------------', request.body)
    jsonData = json.loads(request.body)
    spot = jsonData.get('price')
    index = jsonData.get('symbol')
    quantity = jsonData.get('qty', None)
    offlineOrder = jsonData.get('offlineOrder', None)
    mobile = jsonData.get('mobile', None)

   
    strike, qty = getStrikePrice(spot, index, "SELL")
    _token, _key = getToken(mobile)
   
    tradeUser = TradeUser.objects.get(fyer_key = _key)
    if quantity:
        qty = quantity
    else:
        if index == 'BANKNIFTY':
            qty = tradeUser.bn_option_quantity
        elif index == 'NIFTY':
            qty = tradeUser.nf_option_quantity
    data = {
        "symbol": strike,
        "qty":qty,
        "type":2,
        "side":1,
        "productType":"MARGIN",
        "limitPrice":0,
        "stopPrice":0,
        "validity":"DAY",
        "disclosedQty":0,
        "offlineOrder": True if offlineOrder and offlineOrder == "True"  else False,
        "orderTag":"tag1"
    }
    
    
    print(tradeUser)
    session = fyersModel.FyersModel(client_id=_key, token=_token)
    try:
        response = session.exit_positions(data={})
        savingResponse(tradeUser.id, response, request.path, strike)
        
        buytrigger = True

templates/trade/tokengenerate.html
<!DOCTYPE html>
<html lang="en-us" dir="ltr">
   <head>
      <title>Trade Setup | Token Generation | Django site admin</title>
      <link rel="stylesheet" href="/static/admin/css/base.css">
      <link rel="stylesheet" href="/static/admin/css/dark_mode.css">
      <script src="/static/admin/js/theme.js" defer></script>
      <link rel="stylesheet" href="/static/admin/css/nav_sidebar.css">
      <script src="/static/admin/js/nav_sidebar.js" defer></script>
      <link rel="stylesheet" href="/static/admin/css/forms.css">
      <script src="/admin/jsi18n/"></script>
      <script src="/static/admin/js/vendor/jquery/jquery.js"></script>
      <script src="/static/admin/js/calendar.js"></script>
      <script src="/static/admin/js/jquery.init.js"></script>
      <script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
      <script src="/static/admin/js/core.js"></script>
      <script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
      <script src="/static/admin/js/actions.js"></script>
      <script src="/static/admin/js/urlify.js"></script>
      <script src="/static/admin/js/prepopulate.js"></script>
      <script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
      <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
      <link rel="stylesheet" href="/static/admin/css/responsive.css">
      <meta name="robots" content="NONE,NOARCHIVE">
   </head>
   <body class=" app-trade model-tradeuser change-form"
      data-admin-utc-offset="19800">
      <a href="#content-start" class="skip-to-content-link">Skip to main content</a>
      <!-- Container -->
      <div id="container">
         <!-- Header -->
         <div id="header">
            <div id="branding">
               <h1 id="site-name"><a href="/admin/">Django administration</a></h1>
            </div>
            <div id="user-tools">
               Welcome,
               <strong>admin</strong>.
               <a href="/">View site</a> /
               <a href="/admin/password_change/">Change password</a> /
               <form id="logout-form" method="post" action="/admin/logout/">
                  <input type="hidden" name="csrfmiddlewaretoken" value="cX9pZ0eDN2DIHvPhj65IR2fTzOUKQ9nC68dVZ3nDMBXd0U2ilpn8ykb99xi9KIC1">
                  <button type="submit">Log out</button>
               </form>
               <button class="theme-toggle">
                  <div class="visually-hidden theme-label-when-auto">Toggle theme (current theme: auto)</div>
                  <div class="visually-hidden theme-label-when-light">Toggle theme (current theme: light)</div>
                  <div class="visually-hidden theme-label-when-dark">Toggle theme (current theme: dark)</div>
                  <svg aria-hidden="true" class="theme-icon-when-auto">
                     <use xlink:href="#icon-auto" />
                  </svg>
                  <svg aria-hidden="true" class="theme-icon-when-dark">
                     <use xlink:href="#icon-moon" />
                  </svg>
                  <svg aria-hidden="true" class="theme-icon-when-light">
                     <use xlink:href="#icon-sun" />
                  </svg>
               </button>
            </div>
         </div>
         <!-- END Header -->
         <nav aria-label="Breadcrumbs">
            <div class="breadcrumbs">
               <a href="/admin/">Home</a>
               &rsaquo; <a href="/admin/trade/">Trade</a>
               &rsaquo; <a {% if broker == 'upstox'%} href="/admin/trade/upstoxuser/" {%else %} href="/admin/trade/tradeuser/" {% endif %} > 
                  Trade users</a>
               
            </div>
         </nav>
         <div class="main" id="main">
            <button class="sticky toggle-nav-sidebar" id="toggle-nav-sidebar" aria-label="Toggle navigation"></button>
            {% comment %} <nav class="sticky" id="nav-sidebar" aria-label="Sidebar">
               <input type="search" id="nav-filter"
                  placeholder="Start typing to filter…"
                  aria-label="Filter navigation items">
               <div class="app-auth module">
                  <table>
                     <caption>
                        <a href="/admin/auth/" class="section" title="Models in the Authentication and Authorization application">Authentication and Authorization</a>
                     </caption>
                     <tr class="model-group">
                        <th scope="row"><a href="/admin/auth/group/">Groups</a></th>
                        <td><a href="/admin/auth/group/add/" class="addlink">Add</a></td>
                     </tr>
                     <tr class="model-user">
                        <th scope="row"><a href="/admin/auth/user/">Users</a></th>
                        <td><a href="/admin/auth/user/add/" class="addlink">Add</a></td>
                     </tr>
                  </table>
               </div>
               <div class="app-trade module current-app">
                  <table>
                     <caption>
                        <a href="/admin/trade/" class="section" title="Models in the Trade application">Trade</a>
                     </caption>
                     <tr class="model-traderesponse">
                        <th scope="row"><a href="/admin/trade/traderesponse/">Trade responses</a></th>
                        <td><a href="/admin/trade/traderesponse/add/" class="addlink">Add</a></td>
                     </tr>
                     <tr class="model-tradeuser current-model">
                        <th scope="row"><a href="/admin/trade/tradeuser/" aria-current="page">Trade users</a></th>
                        <td><a href="/admin/trade/tradeuser/add/" class="addlink">Add</a></td>
                     </tr>
                  </table>
               </div>
            </nav> {% endcomment %}
            <div id="content-start" class="content" tabindex="-1">
               <!-- Content -->
               <div id="content" class="colM">
                  <h1>Generate Token for <b>{{trader_name}}</b> user</h1>
                  
                  <div id="content-main">
                     {% comment %} <ul class="object-tools">
                        <li>
                           <a href="/admin/trade/tradeuser/6/history/" class="historylink">History</a>
                        </li>
                     </ul> {% endcomment %}
                     <form method="post" id="tradeuser_form" novalidate>
                        {% csrf_token %}
                        <div>
                           <fieldset class="module aligned ">
                              <div class="form-row field-trader_name">
                                 <div>
                                    <div class="flex-container">
                                       <label class="required" for="id_trader_name">Enter Pin: </label>
                                       <input type="number" name="otp_pin" value="" class="vTextField" maxlength="50" required id="id_trader_pin">
                                    </div>
                                 </div>
                              </div>
                              
                           </fieldset>
                           <div class="submit-row">
                              <input type="submit" value="Save" class="default" name="_save">
                              
                           </div>
                           <script id="django-admin-form-add-constants"
                              src="/static/admin/js/change_form.js"
                              async></script>
                           <script id="django-admin-prepopulated-fields-constants"
                              src="/static/admin/js/prepopulate_init.js"
                              data-prepopulated-fields="[]"></script>
                        </div>
                     </form>
                  </div>
                  <br class="clear">
               </div>
               <!-- END Content -->
               <div id="footer"></div>
            </div>
         </div>
      </div>
      <!-- END Container -->
      <!-- SVGs -->
      <svg xmlns="http://www.w3.org/2000/svg" class="base-svgs">
         <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-auto">
            <path d="M0 0h24v24H0z" fill="currentColor"/>
            <path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2V4a8 8 0 1 0 0 16z"/>
         </symbol>
         <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-moon">
            <path d="M0 0h24v24H0z" fill="currentColor"/>
            <path d="M10 7a7 7 0 0 0 12 4.9v.1c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2h.1A6.979 6.979 0 0 0 10 7zm-6 5a8 8 0 0 0 15.062 3.762A9 9 0 0 1 8.238 4.938 7.999 7.999 0 0 0 4 12z"/>
         </symbol>
         <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-sun">
            <path d="M0 0h24v24H0z" fill="currentColor"/>
            <path d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12zm0-2a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM11 1h2v3h-2V1zm0 19h2v3h-2v-3zM3.515 4.929l1.414-1.414L7.05 5.636 5.636 7.05 3.515 4.93zM16.95 18.364l1.414-1.414 2.121 2.121-1.414 1.414-2.121-2.121zm2.121-14.85l1.414 1.415-2.121 2.121-1.414-1.414 2.121-2.121zM5.636 16.95l1.414 1.414-2.121 2.121-1.414-1.414 2.121-2.121zM23 11v2h-3v-2h3zM4 11v2H1v-2h3z"/>
         </symbol>
      </svg>
      <!-- END SVGs -->
   </body>
</html>